name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 21 for Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      # Make Gradle wrapper executable
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Build the JAR using Gradle
      - name: Build JAR with Gradle
        run: ./gradlew build

      # Extract version from build.gradle
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(grep '^version' build.gradle | sed -E "s/version[[:space:]]*=[[:space:]]*['\"]([^'\"]+)['\"]/\1/")
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image with both version and latest tags
      - name: Build and tag the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag kaizenflow/weather-bridge-server:${{ env.version }} \
            --tag kaizenflow/weather-bridge-server:latest

      # Push the Docker image with the version tag
      - name: Push the versioned Docker image
        run: docker push kaizenflow/weather-bridge-server:${{ env.version }}

      # Push the Docker image with the latest tag
      - name: Push the latest Docker image
        run: docker push kaizenflow/weather-bridge-server:latest

  #Deploy Application
  deploy:
    needs: build
    runs-on: [aws-ec2-weather-bridge]
    steps:
      - name: Pull Image from docker hub
        run: docker pull kaizenflow/weather-bridge-server:latest
      - name: Delete Old container
        run: docker rm -f weather-bridge-server
      - name: Run docker container
        run: docker run -d -p 80:8080 -e VISUAL_CROSSING_API_KEY=HV83F3TRNKSE37TUFJ8JEEXP3 --name weather-bridge-server kaizenflow/weather-bridge-server:latest
